image: python:3.5.1

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update # required to install zip
            - apt-get install -y zip # required for packaging up the application
            - pip install boto3==1.3.0 # required for beanstalk_deploy.py
            - zip -r /tmp/artifact.zip . -x .elasticbeanstalk/\*
            - python beanstalk_deploy.py # run the deployment script
